# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""

    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"

    # shared ingress annotations on all services
    annotations:
    #  kubernetes.io/ingress.class: nginx

# Default values for homepage
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pauwels-labs/homepage
  tag: default
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    global:
      kubernetes.io/ingress.class: 'nginx'
    ratelimited:
      kubernetes.io/ingress.class: 'nginx'
      nginx.ingress.kubernetes.io/limit-rpm: '2'
      nginx.ingress.kubernetes.io/limit-rps: '5'
      nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      nginx.ingress.kubernetes.io/limit-rate-after: '100'
      nginx.ingress.kubernetes.io/limit-rate: '50'
  hosts:
    global:
    - host: pauwelslabs.com
      paths:
      - "/"
      - "/static"
    - host: www.pauwelslabs.com
      paths:
      - "/"
      - "/static"
    ratelimited:
    - host: pauwelslabs.com
      paths:
      - "/message"
    - host: www.pauwelslabs.com
      paths:
      - "/message"
  tls:
  - secretName: homepage-tls
    hosts:
    - pauwelslabs.com
    - www.pauwelslabs.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# tls certificate options
tls:
  cert:
    issuer: letsencrypt-prod
    cn: pauwelslabs.com
    urls:
    - pauwelslabs.com
    - www.pauwelslabs.com
