apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/rust/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-rustup
          resources: {}
        - name: build-cargo-install
          resources: {}
        - image: gcr.io/jenkinsxio/builder-rust:2.1.150-769
          name: build-copy-bin-custom
          resources: {}
          script: |
            #!/bin/sh
            cp ~/.cargo/bin/homepage .
        - image: gcr.io/jenkinsxio/builder-rust:2.1.150-769
          name: build-debug
          resources: {}
          script: |
            #!/bin/sh
            sleep 999999
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
